### ISSUE TITLE
[Feat] Improving developer experience

### ISSUE THREAD

**Issue by AlejandroSuero** [supermaven-inc/supermaven-nvim#24]
# Motivation

When I was working on the files, some have **trailing whitespaces**, and there is no formatting or linting rules. So every time I format the file I have to undo it so it doesn't change the whole file.

## Proposal

- **Linter**: I will personally go for [selene](https://github.com/Kampfkarren/selene) (a more updated and better approach than [luacheck](https://github.com/mpeterv/luacheck))
- **Formatter**: [stylua](https://github.com/JohnnyMorganz/StyLua) is the standard for `.lua` files, so I would go with this choice.

### Linters

- Selene:

<details>
<summary>Expand to see configuration</summary>

```toml
# selene.toml or .selene.toml
std="neovim" # looks for a `neovim.yml` file to use as configuration

[rules]
global_usage = "warn"
deprecated = "warn" # If changed to `allow` it will rely in `lua_ls` diagnostics alone
multiple_statements = "warn"
incorrect_standard_library_use = "allow" # This is for cases like `string.format`, `package.config`, etc.
mixed_table = "allow"
unused_variable = "warn"
undefined_variable = "warn"
```

```yml
# neovim.yml
---
base: lua51 # to use lua5.1 what Neovim uses

globals:
  jit:
    any: true
  vim:
    any: true
  assert:
    args:
      - type: bool
      - type: string
        required: false
  after_each:
    args:
      - type: function
  before_each:
    args:
      - type: function
  describe:
    args:
      - type: string
      - type: function
  it:
    args:
      - type: string
      - type: function
```

</details>

---

- Luacheck: (pulled from [plenay.nvim](https://github.com/nvim-lua/plenary.nvim))

<details>
<summary>Expand to see configuration</summary>

```lua
-- .luacheckrc
-- Rerun tests only if their modification time changed.
cache = true

std = luajit
codes = true

self = false

-- Glorious list of warnings: https://luacheck.readthedocs.io/en/stable/warnings.html
ignore = {
  "212", -- Unused argument, In the case of callback function, _arg_name is easier to understand than _, so this option is set to off.
  "122", -- Indirectly setting a readonly global
}

globals = {
  "_",
  "_PlenaryLeafTable",
  "_PlenaryBustedOldAssert",
  "_AssociatedBufs",
}

-- Global objects defined by the C code
read_globals = {
  "vim",
}

exclude_files = {
  "lua/plenary/profile/lua_profiler.lua",
  "lua/plenary/profile/memory_profiler.lua",
  "lua/plenary/async_lib/*.lua",
}

files = {
  ["lua/plenary/busted.lua"] = {
    globals = {
      "describe",
      "it",
      "pending",
      "before_each",
      "after_each",
      "clear",
      "assert",
      "print",
    },
  },
  ["lua/plenary/async/init.lua"] = {
    globals = {
      "a",
    },
  },
  ["lua/plenary/async/tests.lua"] = {
    globals = {
      "describe",
      "it",
      "pending",
      "before_each",
      "after_each",
    },
  },
}
```

</details>

### Formatter

- Stylua:

<details>
<summary>Expand to see configuration</summary>

```toml
# stylua.toml or .stylua.toml
column_width = 120
line_endings = "Unix"
indent_type = "Spaces"
indent_width = 2
quote_style = "AutoPreferDouble"
call_parentheses = "Always"
collapse_simple_statement = "Never"

[sort_requires]
enabled = true
```

</details>

We can also add a `Makefile` to use `make lint` and `make format`.

```Makefile
lint:
   @printf "\nRunning linter\n"
   @selene --display-style quiet --config ./selene.toml lua/supermave-nvim
   # @luacheck lua/supermaven-nvim
   @printf "\Running formatter check\n"
   @stylua --color always -f ./stylua.toml --check .

format:
   @printf "\nFixing all fixable formatting problems\n"
   @stylua --color always -f ./stylua.toml .
```

---

## Integrating them in workflows

- Selene and stylua:

```yml
name: lint

on:
  pull_request:
    branches:
      - main
    paths:
      - "lua/**"
      - "tests/**"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Run selene
        uses: NTBBloodbath/selene-action@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --display-style quiet lua/freeze-code

  style-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Lint with stylua
        uses: JohnnyMorganz/stylua-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
          args: --color always --check .
```

> [!NOTE]
>
> Both `stylua` and `selene` are installable from [cargo](https://crates.io/).
>
> We could use a cargo install package and then run `make lint` if
> using the `Makefile` approach.

- Luacheck and stylua:

```yml
name: lint

on:
  pull_request:
    branches:
      - main
    paths:
      - "lua/**"
      - "tests/**"

jobs:
  stylua:
    name: stylua
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: JohnnyMorganz/stylua-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest
          # CLI arguments
          args: --color always --check .

  luacheck:
    name: Luacheck
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Prepare
        run: |
          sudo apt-get update
          sudo apt-get install -y luarocks
          sudo luarocks install luacheck

      - name: Lint
        run: sudo make lint
```
